## you probably need to change or comment/uncomment some of these
#
# The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"
#
# tab delimited samples file ... should have the following 3 columns
# sampleName	path_to_R1_fastq	path_to_R2_fastq
#
samples: "WORKDIR/samples.tsv"
#
# BSJ fasta file
bsjfa: "/data/Ziegelbauer_lab/Sarah/MiSeq_R2/bsjs_020921.fasta"
# divergent primers bed file BED6 format required!
primerbed: "PIPELINE_HOME/resources/primers.bed"
#
bowtie2_alignment_parameters: "--very-sensitive-local"
salmon_parameters: "-l U --maxReadOcc 3 --minAssignedFrags 60"
#
#
#
#
#
#
## you most probably dont need to change these
scriptsdir: "PIPELINE_HOME/scripts"
resourcesdir: "PIPELINE_HOME/resources"
tools: "PIPELINE_HOME/config/tools.yaml"
cluster: "PIPELINE_HOME/config/cluster.json"
adapters: "PIPELINE_HOME/resources/TruSeq_and_nextera_adapters.consolidated.fa"
bsjfadefault: "PIPELINE_HOME/resources/bsjs_020921.fasta.gz"
#
## Resources
#
# hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC
#
# ref_fa: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.fa"
# ref_gtf: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.gtf"
# regions: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.fa.regions"
# star_index_dir: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/STAR_index_no_GTF_2.7.6a"
# ref_bwa_index: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC"
# ref_hisat_index: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC"
# ref_bowtie1_index: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC"
# genepred_w_geneid: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.genes.genepred_w_geneid"
#

