## you probably need to change or comment/uncomment some of these
#
# The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"
#
# tab delimited samples file ... should have the following 3 columns
# sampleName	path_to_R1_fastq	path_to_R2_fastq
#
samples: "WORKDIR/samples.tsv"
#
# BSJ fasta file
# bsjfa: "/data/Ziegelbauer_lab/Sarah/MiSeq_R2/bsjs_020921.fasta"
#
# divergent primers information TSV file which will be converted to BED6 format
# The columns in this files are (see example at the bottom):
# Primer	Chromosome	Start	End	Strand	PrimerSequence_5prime_to_3prime	Reference
primertsv: "PIPELINE_HOME/resources/primers.tsv"
# primerbed: "PIPELINE_HOME/resources/primers.bed"
reffa: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.fa"
#
bowtie2_alignment_parameters: "--very-sensitive-local"
salmon_parameters: "-l U --maxReadOcc 3 --minAssignedFrags 60"
aggregate_quant_rowsum_filter: 50     # aggregate quant.sf across samples and filter out rows <= this filter value
#
#
#
#
#
#
## you most probably dont need to change these
scriptsdir: "PIPELINE_HOME/scripts"
resourcesdir: "PIPELINE_HOME/resources"
tools: "PIPELINE_HOME/config/tools.yaml"
cluster: "PIPELINE_HOME/config/cluster.json"
adapters: "PIPELINE_HOME/resources/TruSeq_and_nextera_adapters.consolidated.fa"
# bsjfadefault: "PIPELINE_HOME/resources/bsjs_020921.fasta.gz"
#
## Resources
#
# hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC
#
# ref_fa: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.fa"
# ref_gtf: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.gtf"
# regions: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.fa.regions"
# star_index_dir: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/STAR_index_no_GTF_2.7.6a"
# ref_bwa_index: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC"
# ref_hisat_index: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC"
# ref_bowtie1_index: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC"
# genepred_w_geneid: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v2/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.genes.genepred_w_geneid"
#

# Primer	Chromosome	Start	End	Strand	PrimerSequence_5prime_to_3prime	Reference
# circ29_F	NC_009333.1	29751	29770	+	ACCAGACGGCAAGGTTTTTA	https://doi.org/10.1073/pnas.1816183115
# circ29_R	NC_009333.1	29641	29663	-	TCGTTAGTCAACCTAGCAAAACA	https://doi.org/10.1073/pnas.1816183115
# circ57_F	NC_009333.1	57271	57290	+	CAACCAAAAGGCAGAGTCGT	https://doi.org/10.1073/pnas.1816183115
# circ57_R	NC_009333.1	57057	57076	-	GGCTGAACCCAAGAACTTCA	https://doi.org/10.1073/pnas.1816183115
# circvIRF4_F	NC_009333.1	88288	88307	-	CTCCGTGTGGATACCAGTGA	10.1128/JVI.01952-18
# circvIRF4_R	NC_009333.1	88746	88764	+	TGGTTCCACGCAACAGTCT	10.1128/JVI.01952-18
# circ97_F	NC_009333.1	98176	98195	-	GGAAGAAGCTCATGGACTGG	https://doi.org/10.1073/pnas.1816183115
# circ97_R	NC_009333.1	97964	97983	+	GACCTAAAAACCCGGAGGAG	https://doi.org/10.1073/pnas.1816183115
# circT0.7_F3	NC_009333.1	118221	118240	+	AGTGAGGAGGGAGGAGGGCA
# circT0.7_R2	NC_009333.1	117701	117722	-	CGCTCTCCCAAACCACACGAAT
# circORF72_F3	NC_009333.1	123582	123601	+	AAGATTAAGGGCCAACGCGA
# circORF72_R1	NC_009333.1	123138	123157	-	TAGTTCCTCAGCTGGCAAGC
# circ1400_F	chr4	37631449	37631468	-	ATGTCTGTTAGTGGGGCTGA	https://doi.org/10.1073/pnas.1816183115
# circ1400_R	chr4	37638469	37638488	+	TATCTGCTACCATCGCCTTT	https://doi.org/10.1073/pnas.1816183115
# circ1741_F	chr7	129015044	129015063	-	TCGTTCCTTACGAATTGGAG	https://doi.org/10.1073/pnas.1816183115
# circ1741_R	chr7	129018113	129018132	+	CTGCCGGATCTGTAACAACT	https://doi.org/10.1073/pnas.1816183115